version: '3.3'
services:
  mysql:
    image: mysql:5.6
    ports: ['3307:3306']
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=monofony_dev
      - MYSQL_USER=symfony
      - MYSQL_PASSWORD=password
  php:
    build: ./.docker/php
    ports: ['9000:9000']
    volumes:
     - ./:/var/www/monofony
  nginx:
    build: ./.docker/nginx
    ports: ['90:80']
    volumes:
      - ./:/var/www/monofony